---
title: "About"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


I'm Daniel Banki, a PhD student in Economics at Universitat Pompeu Fabra in Barcelona, Spain. I work on topics related to judgment and decision making. 

## Writing

You can follow my writing on my [Substack page](https://joyofdiscovery.substack.com/). 

## Social things

I run an in-person, non-fiction book club in Barcelona. More information about it here: [Barcelona Bibliophiles](https://sites.google.com/view/barcelona-bibliophiles/)

I organize [Geoguessr](https://www.geoguessr.com/) parties. Basically, we are staring at Google Street View for some time, trying to figure out where we are in the world. If you are also this type of weird, get in touch to join our group.

## Free mentoring

I was lucky to have people in my life who volunteered their time and effort to mentor me. I cannot pay them back, so I want to pay this forward. 

I offer free mentoring in the following areas: academic and PhD life, economics, psychology, social science research, cultivating a non-fiction reading habit, and everything related to Budapest, Hungary, and the Hungarian language and culture. 

I can do mentoring in English, Hungarian, and Spanish. I'm open to mentoring anybody, from any country, age group, etc. 

If you speak decent Hungarian as a non-native speaker and want to get better, I would be delighted to help you (for free, of course). 

## Contact

I like getting to know interesting people. I'm happy to go for a coffee or a walk with anybody. If you are in Barcelona (or not but want to chat), reach out at [`@banki_daniel`](https://twitter.com/banki_daniel) on Twitter or drop me an email at daniel at danielbanki dot com.
