---
title: "Projects"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Web apps

```{r include=FALSE}
library(gt)
library(dplyr)

project_table <- dplyr::tribble(
  ~Name, ~Description,
  "[CountryMappR](https://danielbanki.shinyapps.io/countries-visited/)", "An app to track the countries (and regions in some countries) I've visited.",
  "[NameguessR](https://danielbanki.shinyapps.io/nameguessr/)", "A game in which you guess a person's nationality from their name.",
  "[Barcelona house price explorer](https://danielbanki.shinyapps.io/barcelona-house-prices-explorer/)", "An interactive app to visualise 2021 house prices in Barcelona."
  
)
```


```{r echo=FALSE}
project_table %>% 
  knitr::kable()

```

## Other
```{r include=FALSE}


other_project_table <- dplyr::tribble(
  ~Name, ~Description,
  "[One day, one country](one-day.html)", "I wrote a couple of paragraphs about a new country every day for some time. I then pulled the plug on the project, focusing on other types of writing instead."
  )
  



```

```{r echo=FALSE}
other_project_table %>% 
  knitr::kable()

```