---
title: "One book, (at least) one idea 5: Junkyard Planet by Adam Minter"
description: |
  Finding general lessons about human nature in unexpected places.
author:
  - name: Daniel Banki
    url: https://twitter.com/banki_daniel
date: 2023-02-05
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
    highlight: default
    highlight_downlit: true
creative_commons: CC BY
categories:
- book reflections
editor_options: 
  markdown: 
    wrap: sentence
preview: junkyard-preview.jpg  
draft: false
---

# Introduction

Junkyard Planet is an excellent book about the waste management industry. It shows what happens with things like scrap metal, plastic, or paper after we throw them away. I love books that explain how an industry works. Especially when an author doesn’t feel the need to continuously pester the reader with his moral judgements, place himself in the centre of attention, or fill the book with irrelevant biographical details of secondary characters. Fortunately, Minter does none of this. 

These types of books are valuable for two reasons. The first (and rather obvious) reason is that they help you become more knowledgeable in a specific area. But more importantly, facts or events that seem industry-specific frequently contain general lessons about human nature. In what follows, I highlight four examples from the book in which the lessons are applicable beyond the fence of a scrapyard or the walls of a recycling facility.


# Leonard Fritz and the value of uncertainty

The year is 1938. Leonard Fritz is a poor young man who makes money extracting something valuable (a type of metal called mill scale) from piles of junk using manual labour. He sells the extracted material to his usual sources for 1.25 USD per ton. One day, a well-dressed man shows up at his worksite and wants to buy this material from him. When Leonard asks him how much he is willing to pay, the man offers him 32 USD per ton. Leonard is baffled by the offer and his response is rather short: “What?”. The man mistakes this reaction for having made a low offer and raises his offer to 36 USD per ton. Leonard happily accepts the offer. 

I found this anecdote interesting for two reasons. Leonard got a good deal because of asymmetric information: the other party didn’t know the going rate of the material. This type of information asymmetry can, in theory, be overcome. For instance, the other party could have gone to some scrapyards to enquire about the going rate. Although seeking out more information sounds like a no-brainer, the costs of doing it can sometimes exceed the expected gain. So, we shouldn’t automatically seek out more information no matter what. Rather, we should try to estimate if the expected benefits of the extra information outweigh the costs of acquiring it. 

This is easier said than done. Sometimes the most difficult part is recognizing that the other party has better information than you do. We don’t know what went through the mind of the man approaching Leonard. But it wouldn’t be unimaginable for people in his position to think that if there is an information asymmetry, it surely must be in his favour. After all, he was a Harvard graduate and the representative of an important company, while Leonard was a 15-year-old manual labourer. The other interesting aspect is the all-too-human tendency to assume that we understand people’s reactions. Many times, we don’t. We should adjust our confidence in our judgments accordingly.

# The backhaul and basic economics

When you take a taxi to a remote area, the taxi driver won’t be happy. Most probably, he will have to drive back to his area in an empty car. Something similar happens with shipping containers when there is a trade imbalance between two countries like the US and China. 

China exports more things than it imports. The containers that make their way to the US packed with Chinese products need to get back to China eventually. This journey is called the backhaul, and shipping companies don’t like it. One option is to just ship empty containers back to China. But if you are a shipping company, anything is better than an empty container—even one filled with recyclable paper. The low demand for containers going to China led to low shipping prices, which meant that materials that weren’t profitable to recycle domestically could be recycled elsewhere—benefitting everyone in the process.

# Metal scrap and Chesterton’s fence

Imagine you observe the following import process: a Chinese customer buys a pile of copper and a pile of zinc from a US scrapyard. The US scrapyard mixes the two materials and ships them to China, where the Chinese recycler employs workers who manually separate the copper from the zinc. You are baffled: Why would a Chinese company pay workers to manually sort the materials when it could just tell the US scrapyard not to mix them in the first place? 

Chesterton’s fence is the idea that you shouldn't try to change something until you understand the reasoning behind how things are currently done. So, if the solution seems too obvious (i.e., tell the scrapyard not to mix the copper and the zinc), maybe there is a good reason why it wouldn’t work. 

In the above example, we omitted a crucial phase in the import process: clearing customs in China. If customs officials are competent, it shouldn’t matter whether the materials come separated or mixed: they represent the same value and should be taxed equally. But if customs officials are incompetent, which was allegedly the case in the early years of scrap imports, then the valuation of the imported metal depends on whether the imported lot looks valuable. A healthy mix of metals of different shapes and sizes, some contaminated with other materials, yet others slightly discoloured, comes as close to looking worthless as it gets. The money that the importer saves on import duties and taxes more than covers the wages of the manual sorters.

As is usually the case in these arms races, the customs officials eventually closed the knowledge gap and started inspecting mixed-metal shipments much more thoroughly. After a while, they did that so vigorously that some importers started preferring shipments consisting of a single metal. The easier customs declaration not only saved time, but it also reduced the risk of theft during the unloading process that mixed-metal shipments were subjected to. 

# Goodhart’s law in recycling

Imagine you generate a fixed amount of trash each week and don’t recycle anything. One day, you decide to collect paper, glass, and plastic in separate containers to recycle them. After calculating how much of your waste is now recycled, you feel good about your progress and commit to increasing the proportion further. In other words, this proportion becomes your measure to track how environmentally responsible you are.

According to Goodhart’s law, once a measure becomes a target, it stops being a good measure. In the above example, the proportion of trash recycled starts out as the measure and ends up being the target. Next time you go to the supermarket, you choose recyclable packaging, even if it’s much heavier or bulkier than non-recyclable packaging. 

Not surprisingly, the proportion of trash recycled increases because of your new choices. It’s not only the proportion of recyclables that increases, however, but trash overall. For example, if you generated 10 kg of trash a week (2 kg of it in recyclables) before the change, you might generate 20 kg of trash (15 kg of it in recyclables) after the change. Even though you are doing better than ever before according to your metric, your environmental impact may have become worse, defying the whole purpose of why you started recycling in the first place.


