---
title: "Around the world 2: Chile"
description: |
  In this post, I visualise Chilean copper production.
author:
  - name: Daniel Banki
    url: https://twitter.com/banki_daniel
date: 08-27-2021
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
    highlight: default
    highlight_downlit: true
creative_commons: CC BY
categories:
  - R
  - ggplot2
  - Around the world
draft: true
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  include = FALSE
)
```


```{r libraries}

library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(gganimate)
library(ragg)
library(magick)
library(forcats)

```

```{r add-fonts}


sysfonts::font_add_google("Pompiere", "pompiere")

```


```{r import-prepare}
data <- read_csv("chile.csv", col_types = cols(.default = "c"), na = c("", "-"))

data <- data %>% 
  pivot_longer(!c(site, owner, unit), names_to = "year", values_to = "production")



data <- data %>% 
  mutate(across(c("site", "owner", "year"), ~as.factor(.))) %>% 
  mutate(production = ifelse(is.na(production), as.numeric(0), as.numeric(production)))

comparison <- c("Total Codelco", "Total Chile", "Total world")

chilean_mines_production <- data %>% filter(!site %in% comparison) %>% 
  filter(production != 0) %>% 
 group_by(year) %>% 
  mutate(rank = row_number(-production))

global_production <- data %>% filter(site %in% comparison)
```




```{r chile-plot}

# to add imported font automatically
showtext::showtext_auto()
chile_plot <- ggplot(chilean_mines_production, aes(rank, group = site)) + 
  geom_col(aes(y = production, fill = owner), width = 0.5, position = position_dodge(0.7)) +
  geom_text(aes(y = -50, label = site),
            vjust = 0.2,
            hjust = 1,
            size = 4) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_x_reverse() +
  transition_states(year, transition_length = 1, state_length = 2) +
  ease_aes("quartic-in") +
    labs(title = 'Year: {next_state}') +
  scale_fill_manual(values = c("#e77a19", "#433b35"), guide = guide_legend(title = "Owner")) +
  theme(
    plot.title = element_text(margin = margin(0, 0, 20, 0), hjust = 0.2),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_text(margin = margin(20, 0, 0, 0), hjust = 0.35),
    panel.background = element_rect(fill = "white"),
    panel.grid.major.x = element_line(colour = "lightgray"),
    plot.margin = unit(c(1, 5, 1, 5), "cm"),
  legend.position = c(1.2, .50)) +
  scale_y_continuous(breaks = c(0, 500, 1000, 1500), limits = c(-50, 1500)) +
  labs(x = "", y = "Production (1000 metric tons)") 


chile_gif <- animate(chile_plot, nframes = 2 * length(unique(chilean_mines_production$year)), fps = 5, 
                 width = 624, height = 624)

anim_save("chile.gif", chile_gif)

fig_caption_chile <-  "Chile plot"

showtext::showtext_auto(FALSE)

```

```{r global-plot}


global_production$site <- global_production$site %>% fct_drop() %>% fct_relevel(c("Total world", "Total Chile", "Total Codelco"))

showtext::showtext_auto()
global_plot <- ggplot(global_production, aes(x = as.Date(year, format = "%Y"), y = production, color = site)) + geom_line(size = 1.3) + transition_reveal(as.numeric(year)) +
  scale_y_continuous(labels=function(x) format(x, big.mark = " ", scientific = FALSE)) +
  labs(x = "", y = "Production (1000 metric tons)") +
  scale_color_manual(guide = guide_legend(title = ""),
                     values = c("#663046", "#2c9c91", "#e77a19"), labels = c("World", "Chile", "CODELCO")) + 
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "lightgray"),
     axis.ticks = element_blank(),
    axis.title.y = element_text(margin = margin(0, 20, 0, 0)),
    legend.key.width = unit(1,"cm"),
    legend.key = element_blank(),
    plot.margin = unit(c(1, 1, 1, 1), "cm")
    
    
  )
  

world_gif <- animate(global_plot, nframes = 2 * length(unique(global_production$year)), fps = 10, 
                 width = 624, height = 624)

anim_save("world.gif", world_gif)

fig_caption_world <-  "World plot"
  
showtext::showtext_auto(FALSE) 



```




```{r show-chile, include = TRUE, echo=FALSE, out.width="100%", fig.cap=fig_caption_chile}

chile_gif


```


```{r show-world, include = TRUE, echo=FALSE, out.width="100%", fig.cap=fig_caption_world}

world_gif


```
